before_script:
  - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build_prod
  - deploy_prod
  - rollback

build_image_swarm:
  stage: build_prod
  image: registry.uicgroup.tech/devops/docker:dind
  script:
    - make vars-input
    - make build-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
    - make push-image TAG=$CI_PIPELINE_IID SERVICE_NAME=$CI_PROJECT_NAME PROJECT_NAME=$CI_PROJECT_NAMESPACE REGISTRY=$CI_REGISTRY ENV_TAG=latest
  only:
    - master

deploy_image_swarm:
  stage: deploy_prod
  script:
    - docker service update --with-registry-auth --image registry.uicgroup.tech/tsul/tsul-frontend:$CI_PIPELINE_IID 'tsul_frontend'
  only:
    - master
  tags: 
    - tsul-front-prod

rollback_image_swarm:
  stage: rollback
  script:
    - docker service update --rollback 'tsul_frontend'
  only:
    - master
  when: manual
  tags: 
    - tsul-front-prod

